# Build Stage
FROM node:18-alpine as build-step
WORKDIR /app
COPY energy-analytics/package.json energy-analytics/package-lock.json ./
RUN npm install --legacy-peer-deps
COPY energy-analytics/ ./
RUN npm run build

# Production Stage
FROM nginx:alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
